### ISSUE TITLE
validator fails to performs get() operation on 'list' Type property with multiple sub properties of 'Dict' type

### ISSUE THREAD

**Issue by arahimanshaik** [DMTF/Redfish-Interop-Validator#128] opened 2021-12-07 13:13 UTC
Using Interop-validator against properties with the list of 'Dict' typed sub properties- type property fails as validator check for 'ReadRequirement' assuming it to be a 'Dict' object.

For instance, in Line 256 of [OCPDoorHeatExchangerHardwareManagement profile](https://github.com/opencomputeproject/HWMgmt-OCP-Profiles/blob/master/RackAndPower/OCPDoorHeatExchangerHardwareManagement.v0_0_5.json) we have 'Voltages' property with a list value. Validator assumes it be a 'Dict' type and performs get operation.

Output: 
ERROR - Something went wrong
Traceback (most recent call last):
  File "Redfish-Interop-Validator-master/validateResource.py", line 167, in validateSingleURI
    propMessages, propCounts = interop.validateInteropResource(propResourceObj, objRes, jsondata)
  File "Redfish-Interop-Validator-master/common/interop.py", line 585, in validateInteropResource
    pmsgs, pcounts = validatePropertyRequirement(
  File "Redfish-Interop-Validator-master/common/interop.py", line 394, in validatePropertyRequirement
    msg, success = validateRequirement(profile_entry.get('ReadRequirement', 'Mandatory'), rf_payload_item, parent_object_tuple=rf_payload)
AttributeError: 'list' object has no attribute 'get'
ERROR - Could not finish validation check on this payload

**Comment by mraineri** [comment] 2022-01-07 16:12
While "Voltages" is an array in payload, its property requirements in the profile are still the be defined as a dictionary (not an array of dictionaries). The intent is the requirements specified applies across the entire array of objects in the response body. At this time, the profile has no method to isolate singular array members for specific requirements.

Based on the link provided, the "Voltages" definition in your profile needs to be corrected to the following:

```
        "Voltages": {
          "PropertyRequirements": {
            "Name": "VRM1 Voltage",
            "SensorNumber": {},
            "Status": {},
            "ReadingVolts": {},
            "PhysicalContext": "VoltageRegulator"
          }
        }
```

**Comment by mraineri** [comment] 2022-01-07 16:14
Now that I'm looking at the requirements specified, this seems too specific based on the intent of interop profiles. We never intended it to be used to establish product requirements for a specific product. More specifically, enforcing a "Name" value for a specific voltage goes beyond our intent.

**Comment by mraineri** [comment] 2024-02-15 13:36
Closing; issue is caused by profile syntax error.

**Closed by mraineri** 2024-02-15 13:36 UTC
