### ISSUE TITLE
When The value Mandatory is changed to Recommended, still the profile is failing to pass the parameters.

### ISSUE THREAD

**Issue by nimmalagautam** [DMTF/Redfish-Interop-Validator#114] opened 2020-11-20 13:54 UTC
Hello,
we are trying to validation our profiles using the below command:
**python3 RedfishInteropValidator.py ODIMBaselineHardwareManagement.v1_0_0.json  -c config/config.ini -v**

1. For the Below, ReadRequirement is Recommended for the parameters "EventGroupId": {}, "EventID": {} "EventTimestamp"{},"Message": {},"MessageArgs": {},"MessageId": {}, "OriginOfCondition": {}, "Severity": {} , but still the result is showing the field as mandatory and failing.

"ActionRequirements": {
        "SubmitTestEvent": {
          "ReadRequirement": "Recommended",
          "Purpose": "Ability to generate a test event",
          "Parameters": {
            "EventGroupId": {},
            "EventID": {},
            "EventTimestamp": {},
            "Message": {},
            "MessageArgs": {},
            "MessageId": {},
            "OriginOfCondition": {},
            "Severity": {}
          }
        }
      }
    },

The output of the profile validation:

ODIMBaselineHardwareManagement   -- #EventService.SubmitTestEvent.ReadRequirement | Recommended | Any | Exists | PASS
-- | -- | -- | -- | --
ODIMBaselineHardwareManagement --   #EventService.SubmitTestEvent.EventGroupId.ReadRequirement | Mandatory | Must Exist | DNE | FAIL
ODIMBaselineHardwareManagement --   #EventService.SubmitTestEvent.EventID.ReadRequirement | Mandatory | Must Exist | DNE | FAIL
ODIMBaselineHardwareManagement --   #EventService.SubmitTestEvent.EventTimestamp.ReadRequirement | Mandatory | Must Exist | DNE | FAIL
ODIMBaselineHardwareManagement --   #EventService.SubmitTestEvent.Message.ReadRequirement | Mandatory | Must Exist | DNE | FAIL
ODIMBaselineHardwareManagement --   #EventService.SubmitTestEvent.MessageArgs.ReadRequirement | Mandatory | Must Exist | DNE | FAIL
ODIMBaselineHardwareManagement --   #EventService.SubmitTestEvent.MessageId.ReadRequirement | Mandatory | Must Exist | DNE | FAIL
ODIMBaselineHardwareManagement --   #EventService.SubmitTestEvent.OriginOfCondition.ReadRequirement | Mandatory | Must Exist | DNE | FAIL
ODIMBaselineHardwareManagement --   #EventService.SubmitTestEvent.Severity.ReadRequirement | Mandatory | Must Exist | DNE | FAIL

Please let us know why we are getting the fields as Mandatory even after changing to Recommended.
NOTE: we can see only SubmitTestEvent.ReadRequirement as Recommended, but not the parameters under it

2. For the Below, ReadRequirement, and WriteRequirement is Recommended in the profile. 
"Location": {
          "ConditionalRequirements": [
            {
              "Purpose": "Location for RackGroup",
              "CompareProperty": "ChassisType",
              "CompareType": "Equal",
              "CompareValues": [
                "Rack",
                "RackGroup"
              ],
              "ReadRequirement": "Recommended",
              "WriteRequirement": "Recommended"
            }
          ]

But still, the Results show as Mandatory and FAIL for Location.
ODIMBaselineHardwareManagement   -- Location.ReadRequirement | Mandatory | Must Exist | DNE | FAIL
-- | -- | -- | -- | --

Please let us know how to get this passed with Recommended

**Comment by tomasg2012** [comment] 2020-11-20 19:58
By default, the tool expects all parameters to be mandatory.  Unsure if this was expected to be by design when written.  

You could get around this by not wrapping your ReadRequirement with a conditional.  it seems the program doesn't seem to read those for actions, which will have to be considered.

**Comment by mraineri** [comment] 2020-11-20 20:40
Discussion from today: At the very least, the tool needs to be able to inspect the ActionInfo for this action to check if given parameters are supported. However, ActionInfo isn't going to be mandatory, so if ActionInfo isn't found, we just simply cannot test the parameter requirements.

**Comment by mraineri** [comment] 2021-01-15 20:52
@nimmalagautam can you try the branch "action-info-warning"? @tomasg2012 believes those changes should address your problem.

**Comment by mraineri** [comment] 2021-01-29 20:55
Closing; this issue should be resolved with the latest PR. If not, please reopen.

**Closed by mraineri** 2021-01-29 20:55 UTC
